const { DEVDUO } = require('../config/constants');

class DevDuoEngine {
  constructor() {
    this.status = 'STOPPED';
    this.activeModel = null;
    this.tokenLimit = DEVDUO.MODELS.LITE.tokens;
  }

  async init(model = 'LITE') {
    console.log(`Initializing DevDuo ${model}...`);
    this.activeModel = DEVDUO.MODELS[model];
    this.tokenLimit = this.activeModel.tokens;
    this.status = 'READY';
    return { status: 'ready', model: this.activeModel };
  }

  async generateCode(prompt) {
    if (this.status !== 'READY') throw new Error('Engine not initialized');
    return {
      prompt,
      generated: `// Generated by DevDuo ${this.activeModel.size} model\nfunction example() { return "code"; }`,
      tokensUsed: Math.min(prompt.length / 4, this.tokenLimit)
    };
  }

  getStatus() {
    return { ...this, models: DEVDUO.MODELS };
  }
}

module.exports = new DevDuoEngine();
