const fs = require('fs-extra');
const path = require('path');
const { DEVDUO } = require('../config/constants');
const twin = require('../entanglement-twins/state-manager');

class DevDuoEngine {
  constructor() {
    this.status = 'STOPPED';
    this.activeModel = null;
    this.tokenLimit = 1024;
    this.modelPath = DEVDUO.MODELS.LITE.path;
  }

  async init(model = 'LITE') {
    console.log(`🔄 Initializing DevDuo ${model}...`);
    
    if (!DEVDUO.MODELS[model]) throw new Error(`Model ${model} not found`);
    
    this.activeModel = DEVDUO.MODELS[model];
    this.tokenLimit = this.activeModel.tokens;
    this.modelPath = path.resolve(this.activeModel.path);
    // ✅ Ensure model directory exists
    await fs.ensureDir(this.modelPath);
    
    this.status = 'READY';
    
    // ✅ Sync state to twin
    twin.update({
      devduo: {
        ready: true,
        activeModel: model,
        tokenLimit: this.tokenLimit,
        memoryUsage: this.activeModel.size
      }
    }, 'DEVDUO_ENGINE');
    return { status: 'ready', model: this.activeModel };
  }

  async generateCode(prompt, maxTokens = 1024) {
    if (this.status !== 'READY') throw new Error('AI Engine not initialized. Call /api/ai/init first.');
    
    const tokensUsed = Math.min(Math.ceil(prompt.length / 4), maxTokens, this.tokenLimit);
    
    return {
      prompt,
      generated: `// Generated by DevDuo ${this.activeModel.size} Model\n// Tokens used: ${tokensUsed}\n\nfunction generatedCode() {\n  return "Code output for: ${prompt.substring(0, 50)}...";\n}`,
      tokensUsed,
      model: this.activeModel
    };
  }

  getStatus() {
    return { status: this.status, activeModel: this.activeModel, tokenLimit: this.tokenLimit };
  }
}

module.exports = new DevDuoEngine();
